Repository rubygems/rubygems.org, pull requests merged in 2018-12, with the labels that each got.

#1831 Add MFA to yanking gems API.
  app/controllers/api/v1/deletions_controller.rb
  test/functional/api/v1/deletions_controller_test.rb
Labels: needs-review

#1837 fix click events on the nav's in Firefox
  app/assets/javascripts/mobile-nav.js
  app/assets/javascripts/popup-nav.js
Labels: needs-review

#1775 Removed default-gems from blacklist for releasing Ruby 2.6.
  lib/patterns.rb
Labels: needs-more-work

#1815 Remove update of linkset through UI
  app/controllers/rubygems_controller.rb
  app/views/rubygems/_aside.html.erb
  app/views/rubygems/edit.html.erb
  config/locales/de.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/nl.yml
  config/locales/pt-BR.yml
  config/locales/zh-CN.yml
  config/locales/zh-TW.yml
  config/routes.rb
  test/functional/rubygems_controller_test.rb
Labels: needs-review

#1849 Fix app crash on unknown format
  app/controllers/email_confirmations_controller.rb
  app/controllers/users_controller.rb
  app/views/mailer/email_confirmation.html.erb
  app/views/mailer/email_reset.erb
  config/application.rb
  config/environments/development.rb
  config/environments/test.rb
  config/initializers/clearance.rb
  config/routes.rb
  test/functional/email_confirmations_controller_test.rb
  test/integration/routing_test.rb
  test/integration/sign_up_test.rb
Labels: needs-review

#1850 Set max limit on page param
  app/controllers/application_controller.rb
  app/controllers/news_controller.rb
  app/controllers/searches_controller.rb
  config/application.rb
  config/locales/de.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/nl.yml
  config/locales/pt-BR.yml
  config/locales/zh-CN.yml
  config/locales/zh-TW.yml
  test/functional/api/v1/searches_controller_test.rb
  test/functional/news_controller_test.rb
  test/functional/searches_controller_test.rb
  test/integration/page_params_test.rb
  test/integration/stats_test.rb
Labels: needs-review

#1504 Use Version#created_at instead of Version#built_at
  app/helpers/pages_helper.rb
  app/models/rubygem.rb
  app/models/version.rb
  app/views/versions/_version.html.erb
  app/views/versions/index.html.erb
  test/functional/rubygems_controller_test.rb
  test/functional/versions_controller_test.rb
  test/unit/helpers/pages_helper_test.rb
  test/unit/rubygem_test.rb
Labels: discussion, enhancement

#1825 Enable multi-factor authentication in UI
  app/controllers/application_controller.rb
  app/controllers/multifactor_auths_controller.rb
  app/controllers/profiles_controller.rb
  app/controllers/sessions_controller.rb
  app/models/user.rb
  app/views/profiles/edit.html.erb
  config/locales/de.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/nl.yml
  config/locales/pt-BR.yml
  config/locales/zh-CN.yml
  config/locales/zh-TW.yml
  test/functional/api/v1/api_keys_controller_test.rb
  test/functional/api/v1/deletions_controller_test.rb
  test/functional/api/v1/owners_controller_test.rb
  test/functional/api/v1/rubygems_controller_test.rb
  test/functional/multifactor_auths_controller_test.rb
  test/functional/sessions_controller_test.rb
  test/integration/profile_test.rb
  test/integration/sign_in_test.rb
  test/unit/user_test.rb
Labels: needs-review

#1869 Fix brakeman warnings and enable build failure for it
  .gitignore
  .travis.yml
  app/models/concerns/rubygem_searchable.rb
  app/views/reverse_dependencies/index.html.erb
  config/brakeman.yml
  script/brakeman
Labels: needs-review

#1786 Add index to web_hooks(user_id, rubygem_id)
  db/migrate/20181022172318_add_index_to_web_hooks.rb
  db/schema.rb
Labels: needs-review

#1865 Improving pt-BR translation
  config/locales/pt-BR.yml
Labels: needs-i18n-review
