Repository rubygems/rubygems.org, pull requests merged in 2018-10, with the labels that each got.

#1759 [FEATURE]: Enable a new versions endpoint which allows querying by creation time
  app/controllers/api/v1/timeframe_versions_controller.rb
  app/models/version.rb
  config/routes.rb
  test/functional/api/v1/timeframe_versions_controller_test.rb
  test/unit/version_test.rb
Labels: discussion, needs-more-work

#1796 Restrict special chars from prefixing new gem names
  app/models/rubygem.rb
  test/unit/rubygem_test.rb
Labels: discussion

#1790 Simplify the reverse_dependencies index view
  app/views/reverse_dependencies/_reverse_dependencies.html.erb
  app/views/reverse_dependencies/_search.html.erb
  app/views/reverse_dependencies/index.html.erb
  config/locales/de.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/nl.yml
  config/locales/pt-BR.yml
  config/locales/zh-CN.yml
  config/locales/zh-TW.yml
Labels: needs-review

#1761 Remove check against otp code reuse
  app/models/user.rb
  db/migrate/20181020173922_remove_users_last_otp_at.rb
  db/schema.rb
  test/unit/user_test.rb
Labels: needs-more-work

#1808 Add database.yml file to .gitignore
  .gitignore
Labels: needs-review

#1720 Update Support Section
  README.md
Labels: needs-review
