Repository rubygems/rubygems.org, pull requests merged in 2018-04, with the labels that each got.

#1642 Fix broken header nav
  app/assets/stylesheets/modules/header.css
  app/assets/stylesheets/modules/search.css
  app/views/layouts/application.html.erb
Labels: needs-more-merging

#1702 display version number on rubygem webpage
  app/assets/stylesheets/modules/shared.css
  app/assets/stylesheets/type.css
Labels: needs-more-merging

#1667 Relative urls and more zh-CN translate
  app/controllers/rubygems_controller.rb
  app/controllers/sessions_controller.rb
  app/views/dashboards/show.html.erb
  app/views/home/index.html.erb
  app/views/layouts/application.html.erb
  app/views/pages/about.html.erb
  app/views/profiles/edit.html.erb
  app/views/rubygems/edit.html.erb
  app/views/sessions/new.html.erb
  app/views/versions/_version.html.erb
  test/functional/dashboards_controller_test.rb
  test/functional/profiles_controller_test.rb
  test/functional/rubygems_controller_test.rb
  test/functional/sessions_controller_test.rb
  test/functional/users_controller_test.rb
Labels: needs-more-work

#1711 Add documenation about confirmation email and fix broken badge
  CONTRIBUTING.md
  README.md
Labels: needs-review
