Repository rubygems/rubygems.org, pull requests merged in 2018-11, with the labels that each got.

#1803 Add missing translation for zh-CN
  config/locales/zh-CN.yml
Labels: needs-i18n-review

#1814 Limit news and popular gem's total entries
  app/controllers/application_controller.rb
  app/controllers/news_controller.rb
  app/controllers/searches_controller.rb
  config/application.rb
  test/functional/news_controller_test.rb
Labels: needs-review

#1753 Two-factor authentication feature in API part.
  app/assets/stylesheets/modules/form.css
  app/controllers/api/v1/api_keys_controller.rb
  app/controllers/api/v1/owners_controller.rb
  app/controllers/api/v1/rubygems_controller.rb
  app/controllers/application_controller.rb
  app/controllers/multifactor_auths_controller.rb
  app/models/user.rb
  app/views/profiles/edit.html.erb
  config/locales/de.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/nl.yml
  config/locales/pt-BR.yml
  config/locales/zh-CN.yml
  config/locales/zh-TW.yml
  config/routes.rb
  test/functional/api/v1/api_keys_controller_test.rb
  test/functional/api/v1/owners_controller_test.rb
  test/functional/api/v1/rubygems_controller_test.rb
  test/functional/multifactor_auths_controller_test.rb
  test/functional/sessions_controller_test.rb
  test/integration/profile_test.rb
  test/integration/sign_in_test.rb
  test/unit/user_test.rb
Labels: needs-review

#1816 Codeclimate issue fixes
  app/assets/javascripts/application.js
  app/assets/javascripts/mobile-nav.js
  app/assets/javascripts/popup-nav.js
  app/helpers/searches_helper.rb
  app/views/searches/_aggregations.html.erb
  config/locales/de.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/nl.yml
  config/locales/pt-BR.yml
  config/locales/zh-CN.yml
  config/locales/zh-TW.yml
  lib/assets/javascripts/clipboard.js
  vendor/assets/javascripts/clipboard.js
Labels: needs-review, refactoring

#1823 Increase email confirmation token expires after time
  app/models/user.rb
  config/application.rb
Labels: needs-review

#1826 Reduce password update by email rate limit to 10 req/10min
  config/initializers/rack_attack.rb
  test/integration/rack_attack_test.rb
Labels: needs-review

#1802 Updated Dutch translation
  config/locales/nl.yml
Labels: needs-i18n-review, needs-more-work

#1832 Add no-store to cache-control header for profile edit
  app/controllers/profiles_controller.rb
Labels: needs-review

#1827 Remove iframe used in github stars
  app/assets/javascripts/application.js
  app/assets/stylesheets/application.css
  app/assets/stylesheets/modules/shared.css
  app/helpers/rubygems_helper.rb
  app/views/rubygems/_aside.html.erb
  app/views/rubygems/_github_button.html.erb
  vendor/assets/javascripts/github_buttons.js
  vendor/assets/stylesheets/github_buttons.css
Labels: needs-review
