Repository rubygems/rubygems.org, pull requests merged in 2019-03, with the labels that each got.

#1900 Update linkset model with spec metadata
  app/models/links.rb
  app/models/version.rb
  test/unit/links_test.rb
Labels: needs-review

#1929 Fix NoMethodError: undefined method 'strip' for [""]:Array
  app/controllers/api/v1/searches_controller.rb
  test/integration/api/v1/search_test.rb
Labels: needs-review

#1920 Moved off container based testing in Travis
  .travis.yml
Labels: needs-review

#1926 Add mfa to password reset
  app/controllers/passwords_controller.rb
  app/views/passwords/otp_prompt.html.erb
  config/locales/de.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/nl.yml
  config/locales/pt-BR.yml
  config/locales/zh-CN.yml
  config/locales/zh-TW.yml
  config/routes.rb
  test/functional/passwords_controller_test.rb
  test/integration/password_reset_test.rb
Labels: needs-review

#1883 add missing translation for zh-TW
  config/locales/zh-TW.yml
Labels: needs-i18n-review

#1708 Add Japanese translation
  config/locales/ja.yml
Labels: needs-i18n-review

#1835 Extract dynamic_form's error_messages_for to avoid a wrong i18n scope
  Gemfile
  Gemfile.lock
  app/helpers/dynamic_errors_helper.rb
  app/views/passwords/edit.html.erb
  app/views/profiles/edit.html.erb
  app/views/users/_form.html.erb
  test/unit/helpers/dynamic_errors_helper_test.rb
Labels: needs-more-merging
